blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('blogs.urls')),
]

blogs/urls.py
"""URL patterns for blogs."""
from django.urls import path
from . import views

app_name = 'blogs'

urlpatterns = [
	path('', views.index, name='index'),
	path('topics/', views.topics, name='topics'),
	path('topics/<int:topic_id>', views.topic, name='topic'),
	path('new_topic', views.new_topic, name='new_topic'),
	path('new_entry/<int:topic_id>/', views.new_entry, name='new_entry'),
	path('edit_entry/<int:entry_id>/', views.edit_entry, name='edit_entry'),
	]

users/urls.py
"""URL patterns for users"""

from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = 'users'
urlpatterns = [
	# Login page
	path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
	# Logout page
	path('logout/', auth_views.LogoutView.as_view(), name='logout'),
	# Register page
	path('register/', views.register, name='register'),
	]

blogs/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Topic(models.Model):
	"""Topic of blog post"""
	text = models.CharField(max_length=200)
	date_added = models.DateTimeField(auto_now_add=True)
	owner = models.ForeignKey(User, on_delete=models.CASCADE)

	def __str__(self):
		"""Return a string representation of the model."""
		return self.text

class Entry(models.Model):
	"""Entry for blog post"""
	topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
	text = models.TextField()
	date_added = models.DateTimeField(auto_now_add=True)

	class Meta: verbose_name_plural = 'entries'

	def __str__(self): 
		"""Return string representation of model"""
		text = self.text
		big_text = self.text[:50]
		if text > big_text:
			return big_text + "..."
		else:
			return text

users/models.py
from django.db import models

# Create your models here.

blogs/forms.py
from django import forms

from .models import Topic, Entry

class TopicForm(forms.ModelForm):
	class Meta:
		model = Topic
		fields = ['text']
		labels = {'text': ''}

class EntryForm(forms.ModelForm):
	class Meta:
		model = Entry
		fields = ['text']
		labels = {'text': ''}
		widgets = {'text': forms.Textarea(attrs={'cols': 80})}

blogs/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse
from django.contrib.auth.decorators import login_required

from .models import Topic, Entry
from .forms import TopicForm, EntryForm

# Create your views here.
def index(request):
	"""home page"""
	return render(request, 'blogs/index.html')

@login_required
def topics(request):
	"""shows all the topics"""
	topics = Topic.objects.filter(owner=request.user).order_by('date_added')
	context = {'topics': topics}
	return render(request, 'blogs/topics.html', context)

@login_required
def topic(request, topic_id):
	"""shows one single topic and its entries"""
	topic = get_object_or_404(Topic, id=topic_id)
	# Make sure topic belongs to current user
	if topic.owner != request.user:
		raise Http404

	entries = topic.entry_set.order_by('-date_added')
	context = {'topic': topic, 'entries': entries}
	return render(request, 'blogs/topic.html', context)

@login_required
def new_topic(request):
	"""adds a new topic."""
	if request.method != 'POST':
		# no data submitted- create blank form
		form = TopicForm()
	else:
		# POST data submitted- process data
		form = TopicForm(request.POST)
		if form.is_valid():
			new_topic = form.save(commit=False)
			new_topic.owner = request.user
			new_topic.save()
			return HttpResponseRedirect(reverse('blogs:topics'))

	context = {'form': form}
	return render(request, 'blogs/new_topic.html', context)

@login_required
def new_entry(request, topic_id):
	"""Adds new entry for a chosen topic"""
	topic = Topic.objects.get(id=topic_id)
	if topic.owner != request.user:
		raise Http404

	if request.method != 'POST':
		form = EntryForm()
	else:
		form = EntryForm(data=request.POST)
		if form.is_valid():
			new_entry = form.save(commit=False)
			new_entry.topic = topic
			new_entry.save()
			return HttpResponseRedirect(reverse('blogs:topic', args=[topic_id]))

	context = {'topic': topic, 'form': form}
	return render(request, 'blogs/new_entry.html', context)

@login_required
def edit_entry(request, entry_id):
	"""edits an existing entry"""
	entry = Entry.objects.get(id=entry_id)
	topic = entry.topic
	if topic.owner != request.user:
		raise Http404

	if request.method != 'POST':
		# Initital request- prefill form with the current entry
		form = EntryForm(instance=entry)
	else:
		# POST data submitted, process data.
		form = EntryForm(instance=entry, data=request.POST)
		if form.is_valid():
			form.save()
			return HttpResponseRedirect(reverse('blogs:topic', args=[topic.id]))

	context = {'entry': entry, 'topic': topic, 'form': form}
	return render(request, 'blogs/edit_entry.html', context)

users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm

# Create your views here.

def register(request):
	"""Registers new user"""
	if request.method != 'POST':
		form = UserCreationForm()
	else:
		form = UserCreationForm(data=request.POST)

		if form.is_valid():
			new_user = form.save()
			# Log user in and redirect to home page
			authenticated_user = authenticate(username=new_user.username, password=request.POST['password1'])
			login(request, authenticated_user)
			return HttpResponseRedirect(reverse('blogs:index'))

	context = {'form': form}
	return render(request, 'users/register.html', context)

blogs/templates/blogs/base.html
{% load bootstrap3 %}

<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">

		<title>Blog It!</title>

		{% bootstrap_css %}
		{% bootstrap_javascript %}

	</head>

	<body>

		<!-- Static navbar -->
		<nav class="navbar navbar-default navbar-static-top">
			<div class="container">

				<div class="navbar-header">
					<button type="button" class="navbar-toggle collapsed"
						data-toggle="collapse" data-target="#navbar"
						aria-expanded="false" aria-controls="navbar">
					</button>
					<a class="navbar-brand" href="{% url 'blogs:index' %}">
					Blog It!</a>
				</div>

				<div id="navbar" class="navbar-collapse collapse">
					<ul class="nav navbar-nav">
						<li><a href="{% url 'blogs:topics' %}">Topics</a></li>
					</ul>

					<ul class="nav navbar-nav navbar-right">
						{% if user.is_authenticated %}
							<li><a>Hello, {{ user.username }}.</a></li>
							<li><a href="{% url 'users:logout' %}">Log Out</a></li>
						{% else %}
							<li><a href="{% url 'users:register' %}">Register</a></li>
							<li><a href="{% url 'users:login' %}">Log In</a></li>
						{% endif %}
					</ul>
				</div><!--/.nav-collapse-->
			</div>
		</nav>

		<div class="container">

			<div class="page-header">
				{% block header %}{% endblock header %}
			</div>
			<div>
				{% block content %}{% endblock content %}
			</div>
		</div> <!-- /container -->
	</body>
</html>

blogs/templates/blogs/edit_entry.html
{% extends "blogs/base.html" %}
{% load bootstrap3 %}

{% block header %}
  <h2>Edit entry:</h2>
{% endblock header %}

{% block content %}
	<h2>
		<a href="{% url 'blogs:topic' topic.id %}">{{ topic }}</a>
	</h2>
	<form action="{% url 'blogs:edit_entry' entry.id %}" method='post'>

		{% csrf_token %}
		{% bootstrap_form form %}

		{% buttons %}
		<button name='submit' class= "btn btn-primary">save changes</button>
		{% endbuttons %}
		
	</form>

{% endblock content %}

blogs/templates/blogs/index.html
{% extends 'blogs/base.html' %}

{% block header %}
  <div class='jumbotron'>
  	 <h1>Track your ideas.</h1>
  </div>
{% endblock header %}

{% block content %}
  <h2>
  	<a href="{% url 'users:register' %}">Register an account</a> to start keeping track of what's important to you.
  </h2>
  <h2>
  	Whenever you think of a topic that inspires you, make a new entry and begin to put your ideas to life!
  </h2>

{% endblock content %}

blogs/templates/blogs/new_entry.html
{% extends "blogs/base.html" %}
{% load bootstrap3 %}

{% block header %}
  <h2>Add a new entry:</h2>
{% endblock header %}

{% block content %}
	<h2>
		<a href="{% url 'blogs:topic' topic.id %}">{{ topic }}</a>
	</h2>
	<form action="{% url 'blogs:new_entry' topic.id %}" method='post'>
	
		{% csrf_token %}
		{% bootstrap_form form %}

		{% buttons %}
		<button name="submit" class="btn btn-primary">add entry</button>
		{% endbuttons %}

	</form>

{% endblock content %}

blogs/templates/blogs/new_topic.html
{% extends "blogs/base.html" %}
{% load bootstrap3 %}

{% block header %}
  <h2>Add a new topic:</h2>
{% endblock header %}

{% block content %}
	<form action="{% url 'blogs:new_topic' %}" method='post' 
		class="form">

		{% csrf_token %}
		{% bootstrap_form form %}

		{% buttons %}
		<button name="submit" class="btn btn-primary">add topic</button>
		{% endbuttons %}
		
	</form>

{% endblock content %}

blogs/templates/blogs/topic.html
{% extends 'blogs/base.html' %}

{% block header %}
  <h2>{{ topic }}</h2>
{% endblock header %}

{% block content %}
<p>
	<a href="{% url 'blogs:new_entry' topic.id %}">add new entry</a>
</p>

{% for entry in entries %}
  <div class="panel panel-default">
  	<div class="panel-heading">
  		<h3>
  			{{ entry.date_added|date:'M d, Y H: i' }}
  		  <small>
  		  	<a href="{% url 'blogs:edit_entry' entry.id %}">
  		  	edit entry</a>
  		  </small>
  		 </h3>
  		</div>
  	</div>
  	<div class ="panel-body">
  		{{ entry.text|linebreaks }}
  	</div>
  </div> <!-- panel -->

{% empty %}
	<li>
		There are no entries for this topic yet.
	</li>
{% endfor %}

{% endblock content %}

blogs/templates/blogs/topics.html
{% extends "blogs/base.html" %}

{% block header %}
  <h1>Topics</h1>
{% endblock header %}

{% block content %}

<ul>
	{% for topic in topics %}
		<li>
		  <h3>
			<a href="{% url 'blogs:topic' topic.id %}">{{ topic }}</a>
		  </h3>
		</li>
	{% empty %}
		<li>No topics have been added. yet.</li>
	{% endfor %}
</ul>

<h3><a href="{% url 'blogs:new_topic' %}">Add a new topic:</a></h3>

{% endblock content %}

users/templates/users/login.html
{% extends "blogs/base.html" %}
{% load bootstrap3 %}

{% block header %}
  <h2>Log in to your account</h2>
{% endblock header %}

{% block content %}

	<form method="post" action="{% url 'users:login' %}" class="form">
	  {% csrf_token %}
	  {% bootstrap_form form %}

	 {% buttons %}
		<button name="submit" class="btn btn-primary">log in</button>
	 {% endbuttons %}

	<!-- tells django to redirect to index.html after logging in-->
	 <input type="hidden" name="next" value="{% url 'blogs:index'%}" /> 
	</form>

{% endblock content %}

users/templates/users/register.html
{% extends "blogs/base.html" %}
{% load bootstrap3 %}

{% block header %}
  <h2>Create your new account</h2>
{% endblock header %}

{% block content %}

	<form method="post" action="{% url 'users:register' %}"class="form">

		{% csrf_token %}
		{% bootstrap_form form %}

		{% buttons %}
		<button name="submit" class="btn btn-primary">register</button>
		{% endbuttons %}

		<!-- tells django where to redirect after registering -->
		<input type="hidden" name="next" value="{% url 'blogs:index' %}" />
	</form>

{% endblock content %}